import { StyleSheet } from "react-native";
import chroma from 'chroma-js';

const styles = StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
    },
    text: {
        color: 'black'
    },
    gridContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        padding: 18
    },
    gridItem: {
        width: '37%', 
        height:'100vh',
        aspectRatio: 1, 
        marginBottom: 10,
        backgroundColor: '#ccc',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10, 
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 3,
        elevation: 5,
    },
    gridItem2: {
        width: '60%', 
        height:'100%',
        aspectRatio: 1, 
        marginBottom: 10,
        backgroundColor: '#aaa',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 3,
        elevation: 5,
    },
    gridItem3: {
        width: '100%', 
        height:'100%',
        aspectRatio: 2.7, 
        marginBottom: 10,
        backgroundColor: '#888',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 3,
        elevation: 5,
    },
    gridItem4: {
        width: '60%', 
        height:'100%',
        aspectRatio: 1.5, 
        marginBottom: 10,
        backgroundColor: '#888',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 3,
        elevation: 5,
    },
    gridItem5: {
        width: '37%', 
        height:'100vh',
        aspectRatio: 2, 
        marginBottom: 10,
        backgroundColor: '#888',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 3,
        elevation: 5,
    },
    gridItemText: {
        fontSize: 18,
        color: '#000',
    },
})

export default styles;